namespace: default

resources:
  - crd/global-resource.kaidotdev.github.io_globalconfigmaps.yaml
  # +kubebuilder:scaffold:crdkustomizeresource
  - cluster_role.yaml
  - cluster_role_binding.yaml
  - deployment.yaml
  - pod_disruption_budget.yaml
  - role.yaml
  - role_binding.yaml
  - service_account.yaml
