apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: global-resource-controller-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: global-resource-controller-leader-election
subjects:
  - kind: ServiceAccount
    name: global-resource-controller
