
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: globalconfigmaps.global-resource.kaidotdev.github.io
spec:
  group: global-resource.kaidotdev.github.io
  names:
    kind: GlobalConfigMap
    listKind: GlobalConfigMapList
    plural: globalconfigmaps
    singular: globalconfigmap
  scope: Cluster
  validation:
    openAPIV3Schema:
      description: GlobalConfigMap is the schema for the runners API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GlobalConfigMapSpec defines the desired state of GlobalConfigMap
          properties:
            excludeNamespaces:
              items:
                type: string
              type: array
            template:
              properties:
                binaryData:
                  additionalProperties:
                    format: byte
                    type: string
                  description: BinaryData contains the binary data. Each key must
                    consist of alphanumeric characters, '-', '_' or '.'. BinaryData
                    can contain byte sequences that are not in the UTF-8 range. The
                    keys stored in BinaryData must not overlap with the ones in the
                    Data field, this is enforced during validation process. Using
                    this field will require 1.10+ apiserver and kubelet.
                  type: object
                data:
                  additionalProperties:
                    type: string
                  description: Data contains the configuration data. Each key must
                    consist of alphanumeric characters, '-', '_' or '.'. Values with
                    non-UTF-8 byte sequences must use the BinaryData field. The keys
                    stored in Data must not overlap with the keys in the BinaryData
                    field, this is enforced during validation process.
                  type: object
              type: object
          required:
          - template
          type: object
        status:
          description: GlobalConfigMapStatus defines the observed state of GlobalConfigMap
          properties:
            targetNamespaces:
              items:
                type: string
              type: array
          type: object
      required:
      - spec
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
